### ISSUE TITLE
Add dimension parameter for operators acting on spatial fields

### ISSUE THREAD

**Issue by vpuri3** [SciML/SciMLOperators.jl#1]
use case: PDE operators as described below:

```julia
""" Operators acting on fields in D-Dimensional space """
abstract type AbstractOperator{T,D} <: AbstractDiffEqOperator{T} end
```

ref to the interface I've built.
https://github.com/vpuri3/PDEInterfaces.jl/blob/master/src/OperatorBasics.jl

**Comment by xtalax** [comment]
`AbstractOperator` sounds too general, I'd suggest `AbstractMultiDimOperator`

**Comment by ChrisRackauckas** [comment]
It's a general nomenclature thing to define the types relative to the package, i.e. `SciMLOperators.jl` would have `AbstactSciMLOperator`.

**Comment by vpuri3** [comment]
change of plans. im gonna try to do my PDEs stuff without the dimension parameter
