### ISSUE TITLE
Dependency on StaticArraysCore instead of StaticArrays?

### ISSUE THREAD

**Issue by oschulz** [SciML/SciMLOperators.jl#108]
Could SciMLOperators depend on StaticArraysCore instead of StaticArrays, or does it need full StaticArrays functionality?

**Comment by ChrisRackauckas** [comment]
It could do core.

**Comment by oschulz** [comment]
Oh, that would be neat!

**Comment by oschulz** [comment]
Merci @ChrisRackauckas !
