### ISSUE TITLE
total.jl file in tests

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLOperators.jl#110]
What are these tests not included?

**Comment by vpuri3** [comment]
Hi @ArnoStrouwen, I didn't exactly get your question. The tests in `test/total.jl` are indeed included in `test/runtests.jl`. 

https://github.com/SciML/SciMLOperators.jl/blob/5ba2bfb81382779276cc83d5b5b8632c018ddb1b/test/runtests.jl#L13

I also ran tests on my personal computer, and the tests indeed run
```julia
Test Summary: | Pass  Total  Time
Full tests    |   23     23  1.5s
  1.502924 seconds (9.51 M allocations: 503.356 MiB, 3.63% gc time, 97.42% compilation time)
```

These tests ensure that different objects in `SciMLOperators`, that are tested individually, do indeed work together as expected. In the near future, we should test downstream libraries such as LinearSolve, OrdinaryDiffEq, SparseDiffTools - when they start using SciMLOperators. We could also add downstream tests to some of my packages that use SciMLOperators such as https://github.com/vpuri3/FourierSpaces.jl, https://github.com/vpuri3/NodalPolynomialSpaces.jl.

**Comment by ArnoStrouwen** [comment]
Oh I seemed to have picked the wrong one, I think it is actually `matrixfree.jl` that is not included?

**Comment by vpuri3** [comment]
close?

**Comment by ArnoStrouwen** [comment]
Solved by https://github.com/SciML/SciMLOperators.jl/pull/112
