### ISSUE TITLE
DiagonalOperator for dot operators?

### ISSUE THREAD

**Issue by AshtonSBradley** [SciML/SciMLOperators.jl#117]
A `.*` array operation can currently be implemented by reshaping to a column and then applying a diagonal matrix cast as `DiagonalOperator`. 

Reshaping uses memory for large arrays, so I wonder if there is scope to handle dot operations in this API since they are equivalent to `DiagonalOperator`?

**Comment by vpuri3** [comment]
DiagonalOperator uses `vec` which is in place, so there shouldn't be any memory allocation, besides 64 bytes for the integer tuple that stores `size` -- negligible for most applications.

if you see a substantial memory footprint with DiagonalOperator and mul! or ldiv! let me know and we'll sort this out. Alternatively if you want to eliminate the size allocation, let me know. there are some view tricks that we can play

**Comment by vpuri3** [comment]
as a rule, no SciMLOperator should allocate when used as in

```julia

cache_operator(L, u) # allocate cache

# allocation free
mul!(v, L, u) # apply
ldiv!(v, L, u) # invert
L(v, u, p, t) # apply
```

**Comment by vpuri3** [comment]
@AshtonSBradley  @ChrisRackauckas close issue?
