### ISSUE TITLE
Bugs with applying tensor product operator

### ISSUE THREAD

**Issue by gaurav-arya** [SciML/SciMLOperators.jl#127]
Just making a note of some bugs with the tensor product operators: (I know it's an in-progress library :)

- 5-arg `mul!` is broken when the batch size `K` is 1
~- Division via `\` (and likely `ldiv!`) is broken in a number of cases~ (Semi-resolved: these cases were non-square.)

Examples of both can be found in the `@test_broken`'d added in #126.

P.S: It's very tempting to directly define 
```julia
inv(L::TensorProductOperator) = 
      TensorProductOperator(InvertedOperator(L.outer), InvertedOperator(L.inner))
```
and then get `ldiv!` and `\` for free by applying this operator, instead of having to write separate logic for those. I tried to push this through, but it didn't quite work out because for `ldiv!` to be efficient you would want to reuse the cache of `L`, but the cache as currently defined isn't quite symmetric between input and output so this becomes a little tricky. (Maybe #84 helps with this approach?)

**Comment by vpuri3** [comment]
what are the error messages?

**Comment by gaurav-arya** [comment]
For the division error:
```
 Test threw exception
  Expression: AB \ v2 ≈ opAB \ v2 ≈ opAB_F \ v2
  DimensionMismatch: new dimensions (11, 5) must be consistent with array size 21
```

For the `mul!` error:
```
 Test threw exception
  Expression: mul!(v3, opABC, u3, α, β) ≈ α * ABC * u3 + β * w3
  StackOverflowError:
```
(The broken tests for making these errors are in #126)

**Comment by vpuri3** [comment]
and is this on current mastro branch, or on? https://github.com/SciML/SciMLOperators.jl/pull/126?

**Comment by gaurav-arya** [comment]
The same operations error on master (they don't use factorizations, just something I discovered while expanding out the tests)

**Comment by gaurav-arya** [comment]
E.g. here's a MWE that runs on master with all the broken tests:
```
using SciMLOperators, LinearAlgebra
using SciMLOperators: InvertibleOperator, ⊗
using Test
@testset "TensorProductOperator" begin for K in [1, 12]
    m1, n1 = 3 , 5
    m2, n2 = 7 , 11
    m3, n3 = 13, 17

    A = rand(m1, n1)
    B = rand(m2, n2)
    C = rand(m3, n3)
    α = rand()
    β = rand()

    AB  = kron(A, B)
    ABC = kron(A, B, C)

    # Inputs
    u2 = rand(n1*n2, K)
    u3 = rand(n1*n2*n3, K)
    # Outputs
    v2 = rand(m1*m2, K)
    v3 = rand(m1*m2*m3, K)

    opAB  = TensorProductOperator(A, B)
    opABC = TensorProductOperator(A, B, C)

    @test_broken AB \ v2 ≈ opAB \ v2
    @test_broken ABC \ v3 ≈ opABC \ v3

    opAB  = cache_operator(opAB,  u2)
    opABC = cache_operator(opABC, u3)

    M3 = m1*m2*m3

    v3=rand(M3,K); w3=copy(v3);

    (K == 1) && @test_broken mul!(v3, opABC, u3, α, β) ≈ α*ABC*u3 + β*w3
end end
```

**Comment by vpuri3** [comment]
ok let me take a look (might take some time my eyes are dislocated rn). in the meantime, can you make the PR only about factorizations so it can be quickly merged? we can make a separate PR for tensor product

**Comment by gaurav-arya** [comment]
Sounds good! Done

**Comment by vpuri3** [comment]
@gaurav-arya , the matrices you are trying to invert here are not square. Should that matter?What behavior is expected when one tries to apply `\` to a nonsquare system?

**Comment by vpuri3** [comment]
In the tests, I've been careful to test `\` and `ldiv!` with only square, invertible systems.

**Comment by gaurav-arya** [comment]
That's a good point, I didn't realize that. I don't know what the expected behaviour should be for `\` with non-square matrix-free ops.

I think only the `mul!` is a bug then?

**Comment by vpuri3** [comment]
It's likely gonna be least square which we should support anyway. 

im making the changes to support the `\` and `ldiv!` case. gonna attack `mul!` after that

**Comment by gaurav-arya** [comment]
Least squares could be tricky, because e.g. from some quick testing it doesn't seem like `(A * B) \ u  ≈ B \ (A \ u)` for rectangular `A` and `B`. Not the most knowledgeable about this though:)

**Comment by vpuri3** [comment]
yes but we shouldn't get a dimension mismatch error. The tests are passing on my side with `1.8.4` so it should be ok

**Comment by ChrisRackauckas** [comment]
QR, SVD, and GMRES at least always give least squares results on non-square operators, so it's a nice generalization that is pretty consistent.

**Comment by gaurav-arya** [comment]
Right, but for a lazily composed operator the inversion rule wouldn't give least squares because `(A * B) \ u ` doesn't equal `B \ (A \ u)`? Not sure if there's anything that can be done about that case though
