### ISSUE TITLE
Out-of-place `update_coefficients`

### ISSUE THREAD

**Issue by gaurav-arya** [SciML/SciMLOperators.jl#165]
There is only limited support for this function in the codebase currently. It would be interesting to see how to do this with minimal code duplication with `update_coefficients!`: if I understand @ChrisRackauckas's "don't mix mutating/not-mutating codes" philosophy correctly, we should not just fall back on a `copy` + `update_coefficients!`

**Comment by vpuri3** [comment]
first, we would need to ask the user to pass a nonallocating `update_func`. Then we use `Setfield.@set!` to form a new object. There's gonna be a bunch of dup.
