### ISSUE TITLE
Implement and test OOP `update_coefficients(L,u,p,t)`, overload `Base.resize!`

### ISSUE THREAD

**Issue by vpuri3** [SciML/SciMLOperators.jl#171]
The latter just entails resizing function caches.

needed for https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917

**Comment by vpuri3** [comment]
@gaurav-arya all `Base.resize!` needs to do is resize cache vectors.

**Comment by vpuri3** [comment]
@ChrisRackauckas what is correct resize behaviour for MatrixOperator?
```julia
A = rand(10,10)
L = MatrixOperator(A)
A_ = resize!(A, 5) # A[1:5,1:5]??
```

**Comment by ChrisRackauckas** [comment]
MatrixOperator should probably just be an error.
