### ISSUE TITLE
Nest `TensorProductOperator`s

### ISSUE THREAD

**Issue by vpuri3** [SciML/SciMLOperators.jl#50]
Want `⊗(A, B, C,...)` for arbitrary number of arguments. Pairwise fusion is much simpler (and likely faster) than writing a general implementation.

https://github.com/SciML/SciMLOperators.jl/issues/12#issuecomment-1149129574

> I'd like to also 3D and multidim tensor products `\otimes(A, B, C) = \otimes(A, \otimes(B, C))`, which is not possible rn. The reason is that the nested `TensorProductOperator` would have to act on a 2D array, and `SciMLOperator`s only act on `AbstractVectors`. <-- this was a conscious decision on my part to only allow left-multiplication/division of `SciMLOperator`s on `AbstractVector`s. Maybe we can get away with some `reshape` trick?

**Comment by vpuri3** [comment]
@xtalax @ChrisRackauckas thoughts on letting SciMLOperators act on `AbstractMatrix`s? Currently SciMLOperators only act on `AbstractVector`s.

**Comment by xtalax** [comment]
`⊗(A...) = ⊗(A[1], ⊗(A[2:end]...)`
`⊗(A) = A`?

**Comment by xtalax** [comment]
I say do it, makes multidimensionality a first class citizen

**Comment by vpuri3** [comment]
RN we think of AbstractMatrix types as additional operators. and have stuff like this
```julia
    @eval function Base.$op(L::AbstractSciMLOperator, A::AbstractMatrix)
        @assert size(A) == size(L)
        $op(L, MatrixOperator($op(A)))
    end
```
which turn `*,+,-(::AbstractMatrix, ::AbstractSciMLOperator)` into lazy composition, addition, etc

**Comment by xtalax** [comment]
sounds good to me, no need to compute until its actually used

**Comment by vpuri3** [comment]
> `⊗(A...) = ⊗(A[1], ⊗(A[2:end]...)`
pairwise application is there. i do it with `reduce`.

> `⊗(A) = A`?
that's in the next PR.

**Comment by xtalax** [comment]
I mean this is an easy way to implement arbitrary number of argument tensor products

**Comment by vpuri3** [comment]
We can also think about implementing a BlockDiagonalOperator type to do mat-mat products with some view/reshape trickery under the hood.  Do you know what the performance cost of something like `mul!(v[:,i], L, view(u, :,i))` would be?

**Comment by vpuri3** [comment]
@xtalax  if we allow for *,\ with AbstractMatrix, we can also extend to AbstractArray with

```julia
for op in (
           :*, :\,
          )
    @eval function Base.$op(L::AbstractSciMLOperator, x::AbstractArray{<:Number,N}) where{N>2}
        N = size(L, 2)
        sz = (size(L, 1), size(x)[2:end]...)

        vv = L * _reshape(x, (N,:))

        _reshape(vv, sz)
    end
end    
```
