### ISSUE TITLE
Setup upstream usage

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLOperators.jl#55]
- [ ] SciMLBase https://github.com/SciML/SciMLBase.jl/pull/183
- [ ] LinearSolve https://github.com/SciML/LinearSolve.jl/pull/141
- [ ] SparseDiffTools https://github.com/JuliaDiff/SparseDiffTools.jl/pull/189
- [ ] DiffEqSensitivity https://github.com/SciML/DiffEqSensitivity.jl/pull/618
- [ ] DiffEqBase https://github.com/SciML/DiffEqBase.jl/pull/768
- [ ] OrdinaryDiffEq https://github.com/SciML/OrdinaryDiffEq.jl/pull/1683
- [ ] StochasticDiffEq https://github.com/SciML/StochasticDiffEq.jl/pull/473

**Comment by vpuri3** [comment]
sorry for busy with other stuff. lets get this done now! :)

**Comment by vpuri3** [comment]
reminder to deprecate update_coefficients! in DiffEqBase

**Comment by vpuri3** [comment]
can we close this?
