### ISSUE TITLE
potential bug - mistaken operator fusion

### ISSUE THREAD

**Issue by vpuri3** [SciML/SciMLOperators.jl#66]
@ChrisRackauckas lazy sum/compose instead?

https://github.com/SciML/SciMLOperators.jl/blob/7f70a6dee148dc2b9ae084fab8a566016399c0a0/src/basic.jl#L226

https://github.com/SciML/SciMLOperators.jl/blob/7f70a6dee148dc2b9ae084fab8a566016399c0a0/src/basic.jl#L232

**Comment by ChrisRackauckas** [comment]
yes lazy unless constant. Are the ScalarOperators not always constant? What's the bug?

**Comment by vpuri3** [comment]
bug = fusion where it should be lazy

**Comment by ChrisRackauckas** [comment]
ahh yes
