### ISSUE TITLE
Closures Performance Impact

### ISSUE THREAD

**Issue by awadell1** [SciML/SciMLOperators.jl#68]
See Chris's comments here: https://discourse.julialang.org/t/sciml-style-a-style-guide-for-stylish-julia-programmers/81672/4

(Here's hoping I posted on the right repo)

**Comment by ChrisRackauckas** [comment]
what about it?

**Comment by vpuri3** [comment]
These functions were modified in https://github.com/SciML/SciMLOperators.jl/pull/94 as `foldl` was having some problem with zygote. So this can be safely closed @awadell1. Thanks :D
