### ISSUE TITLE
[later] pair fwd and bwd operators

### ISSUE THREAD

**Issue by vpuri3** [SciML/SciMLOperators.jl#84]
If you have access to a cheap inverse for an operator, `A`, then it would be very convenient to use that for `LinearAlgebra.ldiv!, Base.\`.

Trivial example: `ldiv!` with diagonal is ~15x slower than `mul!`.
```julia
julia> n=1024;

julia> u=rand(n); v=copy(u); D=Diagonal(copy(u));

julia> @btime mul!($v,$D,$u);
  129.625 ns (0 allocations: 0 bytes)

julia> @btime ldiv!($v,$D,$u);
  2.030 μs (0 allocations: 0 bytes)
```
This will also be useful for passing `jac` to `SplitFunction`. Maybe this could help https://github.com/CliMA/ClimaCore.jl/issues/41 not sure.

I propose extending `InvertibleOperator` as follows:
```julia
struct InvertibleOperator
    A # fwd SciMLOperator
    F # inv
end
```
where `F` can be the inverse (SciML)Operator, or any object with 3 arg mul!, * defined.

**Comment by gaurav-arya** [comment]
If we have a cheap inverse of `A`, we nearly always have a cheap inverse of `A + kI`, so the design should accomodate that case too

**Comment by vpuri3** [comment]
we can create a new type for that and Sherman Morrison formula

**Comment by vpuri3** [comment]
@gaurav-arya do you wanna create a new issue for https://github.com/SciML/SciMLOperators.jl/issues/84#issuecomment-1474527053 with a design idea?

**Comment by gaurav-arya** [comment]
Just did: #180
