### ISSUE TITLE
Type tree and Docs!

### ISSUE THREAD

**Issue by xtalax** [SciML/SciMLOperators.jl#9]
This should be a higher level, more general package, as such it needs good documentation so that people understand the interfaces.

We need:
- [ ] An abstract type tree, with documentation of the interfaces for each abstract type
    - [ ] `AbstractDiffEqOperator`
    - [ ] `AbstractDiffEqLinearOperator` - this should be a SciMLOperator.
    - [ ] `AbstractMatrixFreeOperator`
    - [ ] `AbstractDiffEqCompositeOperator` - This should be a SciMLOperator
- [ ] Docstrings for extended methods
- [ ] Working doc build
- [ ] Examples
- [ ] Migrate and integrate [this](https://diffeq.sciml.ai/stable/features/diffeq_operator/) page, and link in its original location

**Comment by ChrisRackauckas** [comment]
See https://github.com/SciML/SciMLOperators.jl/pull/38#issuecomment-1146772831
